ALTER TABLE product 
ADD COLUMN IF NOT EXISTS average_rating DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS total_reviews INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS image_url VARCHAR(255);
