ALTER TABLE promotion ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE promotion ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE wishlist ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE wishlist ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
